services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Cabag\Simulatebe\:
    resource: '../Classes/*'

  Cabag\Simulatebe\Middleware\BackendUserSimulator:
    autowire: true
    autoconfigure: true
    public: true

  Cabag\Simulatebe\Handler\LogoutHandler:
    autowire: true
    autoconfigure: true
    public: true
